# Generated by Django 4.2 on 2023-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='customer_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='plan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
